# Generated by Django 5.2.7 on 2025-11-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SGCBA', '0007_delete_inscription'),
        ('app_eleve', '0002_eleve_annee_academique_eleve_date_naissance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('periode', models.CharField(choices=[('1er_trimestre', '1er Trimestre'), ('2eme_trimestre', '2ème Trimestre'), ('3eme_trimestre', '3ème Trimestre')], default='1er_trimestre', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_eleve.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_note.matiere')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGCBA.utilisateur')),
            ],
            options={
                'unique_together': {('eleve', 'matiere')},
            },
        ),
    ]
