# Generated by Django 5.2.7 on 2025-11-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='annee_academique',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
    ]
