# Generated by Django 5.2.7 on 2025-10-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom_classe', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_academique', models.CharField(max_length=20)),
            ],
        ),
    ]
