# Generated by Django 5.2.6 on 2025-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_eleve', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('classe', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('tel_tuteur', models.CharField(max_length=15)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'db_table': 'app_inscription_eleve',
            },
        ),
    ]
