# Generated by Django 5.2.7 on 2025-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inscription', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
