# Generated by Django 5.2.7 on 2025-11-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inscription', '0003_inscription_annee_academique'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
