# Generated by Django 5.2.7 on 2025-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inscription', '0004_inscription_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
