# Generated by Django 5.2.7 on 2025-10-27 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ajoute', 'Ajoute'), ('modifye', 'Modifye'), ('efase', 'Efase'), ('konekte', 'Konekte'), ('dekonekte', 'Dekonekte'), ('valide', 'Valide'), ('desaktive', 'Desaktive'), ('telechaje', 'Telechaje')], max_length=20)),
                ('objet_type', models.CharField(max_length=50)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('utilisateur_id', models.IntegerField()),
                ('utilisateur_role', models.CharField(max_length=20)),
                ('utilisateur_username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_journal_log',
                'ordering': ['-date_action'],
            },
        ),
    ]
