# Generated by Django 5.1.5 on 2025-09-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
