# Generated by Django 5.1.5 on 2025-09-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0003_utilisateur_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default='photos_profil/pro.png', upload_to='photos_profil/'),
        ),
    ]
