# Generated by Django 5.2.6 on 2025-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0004_utilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
