# Generated by Django 5.2.6 on 2025-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0004_utilisateur_photo'),
    ]

    operations = [
<<<<<<< HEAD:PROJET_JBN/SGCBA/migrations/0005_utilisateur_token.py
=======
        # migrations.DeleteModel(
        #     name='Inscription',
        # ),
>>>>>>> 1671dfc80e71e61443976d8a3f59211ee6dc2699:PROJET_JBN/SGCBA/migrations/0006_delete_inscription_utilisateur_token.py
        migrations.AddField(
            model_name='utilisateur',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
