# Generated by Django 5.2.6 on 2025-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0004_utilisateur_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_eleve', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('date_naiss', models.DateField()),
                ('classe', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('tel_tuteur', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_eleves/')),
            ],
        ),
    ]
