# Generated by Django 5.2.7 on 2025-10-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0005_inscription'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Inscription',
        # ),
        migrations.AddField(
            model_name='utilisateur',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
