# Generated by Django 5.2.6 on 2025-10-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0005_inscription'),
        ('SGCBA', '0005_utilisateur_token'),
    ]

    operations = [
    ]
