# Generated by Django 5.2.6 on 2025-10-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0006_merge_0005_inscription_0005_utilisateur_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
