aq# Generated by Django 5.2.7 on 2025-11-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0007_delete_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='session_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
