# Generated by Django 5.2.7 on 2025-11-13 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eleve', '0002_eleve_annee_academique_eleve_date_naissance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('1er_trimestre', '1er Trimestre'), ('2eme_trimestre', '2ème Trimestre'), ('3eme_trimestre', '3ème Trimestre')], default='1er_trimestre', max_length=20)),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mention', models.CharField(max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eleve.eleve')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
