# Generated by Django 5.2.7 on 2025-11-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGCBA', '0007_delete_inscription'),
        ('app_bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='genere_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGCBA.utilisateur'),
        ),
    ]
