# Generated by Django 5.2.7 on 2025-10-30 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_classe', '0001_initial'),
        ('app_inscription', '0003_inscription_annee_academique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('justifier', 'Justifier')], default='prezan', max_length=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='app_inscription.inscription')),
                ('klas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_classe.classe')),
            ],
            options={
                'db_table': 'app_presence',
                'unique_together': {('eleve', 'date', 'klas')},
            },
        ),
    ]
