# Generated by Django 5.2.7 on 2025-11-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_classe', '0001_initial'),
        ('app_presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('justifier', 'Justifier')], default='present', max_length=10),
        ),
        migrations.CreateModel(
            name='QRPermanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='fqP5iXOV_iotNsdkftlxug', max_length=32, unique=True)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_classe.classe')),
            ],
            options={
                'db_table': 'app_presence_qr_permanent',
            },
        ),
    ]
