# Generated by Django 5.2.7 on 2025-11-11 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_classe', '0001_initial'),
        ('app_inscription', '0004_inscription_valide'),
        ('app_presence', '0002_alter_presence_statut_qrpermanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrpermanent',
            name='token',
            field=models.CharField(default='6mSeFOVxBL5tyf4r4N2B-g', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='NotificationScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scan', models.DateTimeField(default=django.utils.timezone.now)),
                ('lu', models.BooleanField(default=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_classe.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inscription.inscription')),
            ],
            options={
                'db_table': 'app_presence_notification_scan',
                'ordering': ['-date_scan'],
            },
        ),
    ]
