# Generated by Django 5.2.7 on 2025-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_eleve', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=200)),
                ('classe', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('telephone_tuteur', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves_photos/')),
                ('actif', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
