# Generated by Django 5.2.7 on 2025-11-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
