# Generated by Django 5.2.7 on 2025-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eleve', '0002_eleve_annee_academique_eleve_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
