# Generated by Django 5.2.7 on 2025-10-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(default='Collège Belle Angelot', max_length=200)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('trimestre', models.IntegerField(default=1)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parametres/')),
                ('regle_passage', models.BooleanField(default=False)),
                ('session_duration', models.IntegerField(default=120)),
                ('pw_reset', models.BooleanField(default=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('tel_contact', models.CharField(blank=True, max_length=20)),
                ('backup_auto', models.BooleanField(default=True)),
                ('logs_active', models.BooleanField(default=True)),
            ],
        ),
    ]
